baseURL = "http://example.org/"
languageCode = "en-us"
title = "Timer | Responsive Multipurpose Bootstrap Hugo Template"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1

[[menu.main]]
name    = "About"
url     = "about"
weight  = 2

# Site Params
[params]
home = "Home"
logo = "images/resized-image-Promo.jpg"
dateFormat = "20 February 2021"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "HI, MY NAME IS LUKA & I AM A"
description = ""
# button
btn     = false
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "STUDENT"
[[params.banner.flipText]]
title   = "CYCLIST"
[[params.banner.flipText]]
title   = "GAMER"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT ME"
content = "Hey, I made this website as a project for school. The pourpose of creating it was to learn some programming and doing something myself.I made this website with Hugo and uploaded it with help of GitHub and Netlify. GitHub link is at the bottom of the page."
image   = "images/about/About.jpg"

# Call to Action
[params.cta]
enable  = false
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = false
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/luka.zupan.7524"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = ""

[[params.socialIcon]]
icon = "ion-social-github"
url = "https://github.com/lukazupan"

[[params.socialIcon]]
icon = "ion-social-discord"
url = ""